const DATA_FOR_BLUR =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAQAAAAnOwc2AAAAEUlEQVR42mMMP8mAARiHsiAABeYLS/l90OkAAAAASUVORK5CYII';
const DATA_FOR_BLUR_ALT =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mOslZq/FQAEPwHtski/rwAAAABJRU5ErkJggg==';

export default DATA_FOR_BLUR;
export { DATA_FOR_BLUR_ALT };
