//@ts-nocheck
import IChannel from 'src/interfaces/IChannel';

const CHANNELS: IChannel[] = [
  {
    id: 3,
    attributes: {
      title: 'Mix',
      order: 3,
      description: 'Mix',
      subtitle: 'Хиты всех времён! - LUBIMKA MIX',
      name: 'mix',
      createdAt: '2022-03-21T16:41:40.331Z',
      updatedAt: '2022-03-21T16:41:41.885Z',
      publishedAt: '2022-03-21T16:41:41.878Z',
      locale: 'en',
      stream: {
        id: 3,
        port: '8049',
        baseURL: 'https://a8.radioheart.ru',
        code: 'RH42060',
        user: 'user8049',
      },
      cover: {
        data: {
          id: 1,
          attributes: {
            name: 'w_-fwf3pkSY.jpg',
            alternativeText: 'w_-fwf3pkSY.jpg',
            caption: 'w_-fwf3pkSY.jpg',
            width: 1080,
            height: 1350,
            formats: {
              large: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/large_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'large_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'large_w_-fwf3pkSY.jpg',
                path: null,
                size: 79.86,
                width: 800,
                height: 1000,
              },
              small: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/small_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'small_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'small_w_-fwf3pkSY.jpg',
                path: null,
                size: 29.44,
                width: 400,
                height: 500,
              },
              medium: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/medium_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'medium_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'medium_w_-fwf3pkSY.jpg',
                path: null,
                size: 52.79,
                width: 600,
                height: 750,
              },
              thumbnail: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/thumbnail_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'thumbnail_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'thumbnail_w_-fwf3pkSY.jpg',
                path: null,
                size: 5.39,
                width: 125,
                height: 156,
              },
            },
            hash: 'w_fwf3pk_SY_a7ccfe80a8',
            ext: '.jpg',
            mime: 'image/jpeg',
            size: 92.3,
            url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/w_fwf3pk_SY_a7ccfe80a8.jpg',
            previewUrl: null,
            provider: 'aws-s3',
            provider_metadata: null,
            createdAt: '2022-03-17T15:36:46.264Z',
            updatedAt: '2022-03-17T15:36:46.264Z',
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 4,
    attributes: {
      title: 'Hits',
      order: 4,
      description:
        'Они не возвращаются. Потому что не уходят.\nОни узнаваемы и громко, и тихо.\nОни – звучат у нас.\nХиты всех времён! - LUBIMKA HITS',
      subtitle: 'Хиты всех времён! - LUBIMKA HITS',
      name: 'hits',
      createdAt: '2022-03-22T14:13:05.721Z',
      updatedAt: '2022-03-22T14:13:09.126Z',
      publishedAt: '2022-03-22T14:13:09.117Z',
      locale: 'en',
      stream: {
        id: 4,
        port: '8022',
        baseURL: 'https://a6.radioheart.ru',
        code: 'RH31504',
        user: 'user8022',
      },
      cover: {
        data: {
          id: 2,
          attributes: {
            name: 'hits-min.jpeg',
            alternativeText: 'hits-min.jpeg',
            caption: 'hits-min.jpeg',
            width: 581,
            height: 581,
            formats: {
              small: {
                ext: '.jpeg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/small_hits_min_6bf1feef44.jpeg',
                hash: 'small_hits_min_6bf1feef44',
                mime: 'image/jpeg',
                name: 'small_hits-min.jpeg',
                path: null,
                size: 11.51,
                width: 500,
                height: 500,
              },
              thumbnail: {
                ext: '.jpeg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/thumbnail_hits_min_6bf1feef44.jpeg',
                hash: 'thumbnail_hits_min_6bf1feef44',
                mime: 'image/jpeg',
                name: 'thumbnail_hits-min.jpeg',
                path: null,
                size: 2.57,
                width: 156,
                height: 156,
              },
            },
            hash: 'hits_min_6bf1feef44',
            ext: '.jpeg',
            mime: 'image/jpeg',
            size: 11.48,
            url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/hits_min_6bf1feef44.jpeg',
            previewUrl: null,
            provider: 'aws-s3',
            provider_metadata: null,
            createdAt: '2022-03-22T14:12:07.507Z',
            updatedAt: '2022-03-22T14:12:07.507Z',
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 2,
    attributes: {
      title: 'Disco',
      order: 2,
      description:
        'Начинаем дискотеку! Присоединяйтесь! Современные танцевальные хиты и нестареющая танцевальная классика! Lubimka Disco - настроение в один клик!',
      subtitle: 'Хиты всех времён! - LUBIMKA DISCO',
      name: 'disco',
      createdAt: '2022-03-17T15:39:02.695Z',
      updatedAt: '2022-03-22T14:13:50.645Z',
      publishedAt: '2022-03-17T16:06:27.629Z',
      locale: 'en',
      stream: {
        id: 2,
        port: '8049',
        baseURL: 'https://a8.radioheart.ru',
        code: 'RH42060',
        user: 'user8049',
      },
      cover: {
        data: {
          id: 3,
          attributes: {
            name: 'Retro-min.jpeg',
            alternativeText: 'Retro-min.jpeg',
            caption: 'Retro-min.jpeg',
            width: 561,
            height: 581,
            formats: {
              small: {
                ext: '.jpeg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/small_Retro_min_7ffc3e8277.jpeg',
                hash: 'small_Retro_min_7ffc3e8277',
                mime: 'image/jpeg',
                name: 'small_Retro-min.jpeg',
                path: null,
                size: 29.42,
                width: 483,
                height: 500,
              },
              thumbnail: {
                ext: '.jpeg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/thumbnail_Retro_min_7ffc3e8277.jpeg',
                hash: 'thumbnail_Retro_min_7ffc3e8277',
                mime: 'image/jpeg',
                name: 'thumbnail_Retro-min.jpeg',
                path: null,
                size: 4.78,
                width: 151,
                height: 156,
              },
            },
            hash: 'Retro_min_7ffc3e8277',
            ext: '.jpeg',
            mime: 'image/jpeg',
            size: 37.91,
            url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/Retro_min_7ffc3e8277.jpeg',
            previewUrl: null,
            provider: 'aws-s3',
            provider_metadata: null,
            createdAt: '2022-03-22T14:13:44.477Z',
            updatedAt: '2022-03-22T14:13:44.477Z',
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
  {
    id: 1,
    attributes: {
      title: 'FM',
      order: 1,
      description:
        'Утро. Lubimka.\nДень. Lubimka.\nВечер. Lubimka.\nПри всём богатстве выбора, альтернативы нет. Lubimka. 24\\7 -Lubimka',
      subtitle: null,
      name: 'fm',
      createdAt: '2022-03-17T15:36:53.908Z',
      updatedAt: '2022-04-08T15:11:42.622Z',
      publishedAt: '2022-03-17T16:06:30.222Z',
      locale: 'en',
      stream: {
        id: 1,
        port: '9021',
        baseURL: 'https://a6.radioheart.ru',
        code: 'RH16706',
        user: 'user8021',
      },
      cover: {
        data: {
          id: 1,
          attributes: {
            name: 'w_-fwf3pkSY.jpg',
            alternativeText: 'w_-fwf3pkSY.jpg',
            caption: 'w_-fwf3pkSY.jpg',
            width: 1080,
            height: 1350,
            formats: {
              large: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/large_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'large_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'large_w_-fwf3pkSY.jpg',
                path: null,
                size: 79.86,
                width: 800,
                height: 1000,
              },
              small: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/small_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'small_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'small_w_-fwf3pkSY.jpg',
                path: null,
                size: 29.44,
                width: 400,
                height: 500,
              },
              medium: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/medium_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'medium_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'medium_w_-fwf3pkSY.jpg',
                path: null,
                size: 52.79,
                width: 600,
                height: 750,
              },
              thumbnail: {
                ext: '.jpg',
                url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/thumbnail_w_fwf3pk_SY_a7ccfe80a8.jpg',
                hash: 'thumbnail_w_fwf3pk_SY_a7ccfe80a8',
                mime: 'image/jpeg',
                name: 'thumbnail_w_-fwf3pkSY.jpg',
                path: null,
                size: 5.39,
                width: 125,
                height: 156,
              },
            },
            hash: 'w_fwf3pk_SY_a7ccfe80a8',
            ext: '.jpg',
            mime: 'image/jpeg',
            size: 92.3,
            url: 'https://lubimka-media.s3.eu-central-1.amazonaws.com/w_fwf3pk_SY_a7ccfe80a8.jpg',
            previewUrl: null,
            provider: 'aws-s3',
            provider_metadata: null,
            createdAt: '2022-03-17T15:36:46.264Z',
            updatedAt: '2022-03-17T15:36:46.264Z',
          },
        },
      },
      localizations: {
        data: [],
      },
    },
  },
];

export default CHANNELS;
